CREATE SEQUENCE GENRES_SEQ START 1;
CREATE SEQUENCE PROGRAMMES_SEQ START 1;
CREATE SEQUENCE IMPORT_SEQ START 1;
CREATE TABLE PROGRAMME (
	ID bigint not null,
  	IMDB_ID varchar(255) not null,
	TITLE varchar(1000) not null,
	TITLE_TYPE varchar(255) not null,
	PRIMARY_TITLE varchar(1000) not null,
	ORIGINAL_TITLE varchar(1000) not null,
	START_YEAR integer,
	END_YEAR integer ,
	RUNTIME_MINUTES integer,
	ADULT boolean not null,
	PRIMARY KEY (ID)
);

CREATE INDEX PROGRAMME_ID_INDEX ON PROGRAMME(ID);
CREATE INDEX PROGRAMME_IMDB_ID_INDEX ON PROGRAMME(IMDB_ID);
CREATE INDEX PROGRAMME_TITLE_TYPE_INDEX ON PROGRAMME(TITLE_TYPE);
CREATE INDEX PROGRAMME_TITLE_INDEX ON PROGRAMME(TITLE);
CREATE INDEX PROGRAMME_START_YEAR_INDEX ON PROGRAMME(START_YEAR);
CREATE INDEX PROGRAMME_ADULT_INDEX ON PROGRAMME(ADULT);


CREATE TABLE GENRE(
	ID bigint not null,
	PROGRAMME_ID bigint not null,
	NAME varchar(255) not null,
	FOREIGN KEY (PROGRAMME_ID) REFERENCES PROGRAMME (ID),
	PRIMARY KEY (ID)
);

CREATE INDEX GENRE_ID_INDEX ON GENRE(ID);
CREATE INDEX GENRE_NAME_INDEX ON GENRE(NAME);
CREATE INDEX GENRE_PROGRAMME_ID_INDEX ON GENRE(PROGRAMME_ID);

CREATE TABLE IMPORT (
	ID bigint not null,
  	CHECKSUM varchar(255) not null,
  	PRIMARY KEY (ID)
);
